name = "loreal-routine-builder-api"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment configuration
[env.production]
name = "loreal-routine-builder-api"

[env.development]
name = "loreal-routine-builder-api-dev"

# Add any additional configuration here
[[env.production.vars]]
ENVIRONMENT = "production"
CORS_ORIGIN = "*"
RATE_LIMIT_REQUESTS = "30"
RATE_LIMIT_WINDOW = "60000"

[[env.development.vars]]
ENVIRONMENT = "development"
CORS_ORIGIN = "*"
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "60000"

# Secrets (set via wrangler secret put command):
# OPENAI_API_KEY - Your OpenAI API key
# BING_SEARCH_API_KEY - Your Bing Search API key (optional)
# CLIENT_API_KEY - Optional client authentication key
